version: '1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    volumes:
    - ./:/go-gorm 
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
